stages:
  - test   # Run tests first
  - build  # Run build after tests
  - deploy # Deploy the services and front-end

services:
  - postgres:14.2-bullseye

variables:
  POSTGRES_PASSWORD: test
  DATABASE_URL: postgresql://postgres:test@postgres:5432/postgres

accounts-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd accounts
    - pip install -r requirements.txt
    - python manage.py test

activities-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd activities
    - pip install -r requirements.txt
    - python manage.py test

lint-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 accounts activities

build-front-end-job:
  stage: build
  image: node:lts-bullseye
  variables:
    PUBLIC_URL: https://pillow-case.gitlab.io/lets-do-that
  script:
    - cd ghi  # CHANGE THIS TO THE DIRECTORY THAT HAS package.json
    - npm install
    - npm run build
    - cp build/index.html build/404.html  # Make this a SPA
  artifacts:
    paths:
      - ghi/build/  # Save all of the files in the build path

pages:  # THIS STEP MUST BE NAME PAGES
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
     # THE FIRST PART OF THIS COMMAND MUST BE THE DIRECTORY
     # THAT YOU cd INTO TO BUILD IT PLUS THE build/ AT THE
     # END
    - mv ghi/build/ public
  artifacts:
    paths:
      - public

build-accounts-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # CHANGE THIS TO THE DIRECTORY THAT HAS YOUR Dockerfile
    - cd accounts

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO A MORE MEANINGFUL SERVICE NAME (5 PLACES)
    - docker build -t ${CI_REGISTRY_IMAGE}/accounts:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/accounts:latest ${CI_REGISTRY_IMAGE}/accounts:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/accounts:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/accounts:latest

deploy-accounts-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - build-accounts-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO THE NAME YOU CHOSE FOR THE BUILD STEP (2 PLACES)

    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (2 PLACES)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE /web TO /worker (2 PLACES)
    - docker pull ${CI_REGISTRY_IMAGE}/accounts:latest
    - docker tag ${CI_REGISTRY_IMAGE}/accounts:latest registry.heroku.com/$HEROKU_ACCOUNT_API_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_ACCOUNT_API_APP/web:latest

release-accounts-image-job:  # RENAME THIS
  stage: deploy
  image: node:10.17-alpine
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - deploy-accounts-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (1 PLACE)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE web TO worker (1 PLACE)
    - heroku container:release web --app $HEROKU_ACCOUNT_API_APP

build-activities-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # CHANGE THIS TO THE DIRECTORY THAT HAS YOUR Dockerfile
    - cd activities

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO A MORE MEANINGFUL SERVICE NAME (5 PLACES)
    - docker build -t ${CI_REGISTRY_IMAGE}/activities:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/activities:latest ${CI_REGISTRY_IMAGE}/activities:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/activities:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/activities:latest

deploy-activities-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - build-activities-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO THE NAME YOU CHOSE FOR THE BUILD STEP (2 PLACES)

    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (2 PLACES)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE /web TO /worker (2 PLACES)
    - docker pull ${CI_REGISTRY_IMAGE}/activities:latest
    - docker tag ${CI_REGISTRY_IMAGE}/activities:latest registry.heroku.com/$HEROKU_ACTIVITIES_API_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_ACTIVITIES_API_APP/web:latest

release-activities-image-job:  # RENAME THIS
  stage: deploy
  image: node:10.17-alpine
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - deploy-activities-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (1 PLACE)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE web TO worker (1 PLACE)
    - heroku container:release web --app $HEROKU_ACTIVITIES_API_APP

build-accounts-poller-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # CHANGE THIS TO THE DIRECTORY THAT HAS YOUR Dockerfile
    - cd accounts/poll

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO A MORE MEANINGFUL SERVICE NAME (5 PLACES)
    - docker build -t ${CI_REGISTRY_IMAGE}/accounts-poller:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/accounts-poller:latest ${CI_REGISTRY_IMAGE}/accounts-poller:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/accounts-poller:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/accounts-poller:latest

deploy-accounts-poller-image-job:  # RENAME THIS
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - build-accounts-poller-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # EVERYWHERE IT SHOWS fastapi_api BELOW, CHANGE THOSE
    # TO THE NAME YOU CHOSE FOR THE BUILD STEP (2 PLACES)

    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (2 PLACES)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE /web TO /worker (2 PLACES)
    - docker pull ${CI_REGISTRY_IMAGE}/accounts-poller:latest
    - docker tag ${CI_REGISTRY_IMAGE}/accounts-poller:latest registry.heroku.com/$HEROKU_ACCOUNTS_POLLER_APP/worker:latest
    - docker push registry.heroku.com/$HEROKU_ACCOUNTS_POLLER_APP/worker:latest

release-accounts-poller-image-job:  # RENAME THIS
  stage: deploy
  image: node:10.17-alpine
  needs:
    # CHANGE THIS TO THE JOB NAME FROM THE LAST STEP
    - deploy-accounts-poller-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    # EVERYWHERE IT SHOWS HEROKU_SERVICE_APP BELOW, CHANGE
    # THOSE TO THE VARIABLE NAME YOU CREATED FOR THE CI/CD
    # SETTINGS (1 PLACE)

    # IF THIS IS FOR A BACKGROUND SERVICE LIKE A POLLER,
    # CHANGE web TO worker (1 PLACE)
    - heroku container:release worker --app $HEROKU_ACCOUNTS_POLLER_APP