const category_list = {
    active_life: [
        'atvrentals',
        'bikerentals',
        'challengecourses',
        'climbing',
        'fitness',
        'gokarts',
        'hiking',
        'horsebackriding',
        'jetskis',
        'rafting',
        'skydiving',
        'snorkeling',
        'sports_clubs',
        'swimmingpools',
        'trampoline',
    ],

    night_life: [
        'bars',
        'cocktailbars',
        'comedyclubs',
        'countrydancehalls',
        'danceclubs',
        'jazzandblues',
        'hauntedhouses',
        'hotels',
        'karaoke',
        'lounges',
        'musicvenues',
        'partybusrentals',
        'poolhalls',
        'pubs',
        'sportsbars',
    ],

    shopping: [
        'antiques',
        'artsandcrafts',
        'auctionhouses',
        'cosmetics',
        'deptstores',
        'discountstore',
        'electronics',
        'fashion',
        'fleamarkets',
        'galleries',
        'hobbyshops',
        'homeandgarden',
        'media',
        'outlet_stores',
        'souvenirs',
    ],

    food: [
        'bakeries',
        'burgers',
        'chinese',
        'coffee',
        'desserts',
        'foodtrucks',
        'german',
        'italian',
        'japanese',
        'korean',
        'mediterranean',
        'mexican',
        'polish',
        'sandwiches',
        'steak',
    ],

    indoor: [
        'aquariums',
        'axethrowing',
        'bowling',
        'casinos',
        'coffee',
        'escapegames',
        'indoor_playcenter',
        'lasertag',
        'movietheaters',
        'museums',
        'planetarium',
        'recreation',
        'skatingrinks',
        'virtualrealitycenters',
        'wineries',
    ],

    outdoor: [
        'amusementparks',
        'battingcages',
        'beaches',
        'discgolf',
        'festivals',
        'fishing',
        'hot_air_balloons',
        'lakes',
        'parks',
        'playgrounds',
        'scooterrentals',
        'swimmingpools',
        'tours',
        'zipline',
        'zoos',
    ]
}

export default category_list
