export const active_life = [
    'atvrentals',
    'bikerentals',
    'challengecourses',
    'climbing',
    'fitness',
    'hiking',
    'horsebackriding',
    'rafting',
    'skydiving',
    'swimmingpools',
    'trampoline',
]

export const night_life = [
    'bars',
    'clubcrawl',
    'comedyclubs',
    'countrydancehalls',
    'danceclubs',
    'karaoke',
    'musicvenues',
    'partybusrentals',
    'poolhalls',
]

export const shopping = [
    'antiques',
    'galleries',
    'auctionhouses',
    'cosmetics',
    'deptstores',
    'electronics',
    'fashion',
    'fleamarkets',
    'outlet_stores',
    'souvenirs',
]

export const food = [
    'african',
    'bakeries',
    'burgers',
    'chinese',
    'coffee',
    'desserts',
    'foodtrucks',
    'german',
    'italian',
    'japanese',
    'korean',
    'mediterranean',
    'polish',
    'sandwiches',
    'spanish',
    'steak',
]

export const indoor = [
    'aquariums',
    'axethrowing',
    'bowling',
    'escapegames',
    'indoor_playcenter',
    'lasertag',
    'movietheaters',
    'museums',
    'wineries',
]

export const outdoor = [
    'amusementparks',
    'beaches',
    'fishing',
    'hot_air_balloons',
    'lakes',
    'parks',
    'playgrounds',
    'scooterrentals',
    'swimmingpools',
    'zipline',
    'zoos',
]




// const category_list = [
//     'localservices',
//     'italian',
//     'bars',
//     'food',
//     'beautysvc',
//     'health',
//     'shopping',
//     'education',
//     'nightlife',
//     'fitness',
//     'tours',
//     'medicalspa',
//     'restaurants',
//     'hotels',
//     'transport',
//     'hotelstravel',
//     'airports',
//     'active',
//     'portuguese',
//     'french',
//     'arabian',
//     'arts',
//     'spanish',
//     'museums',
//     'artsandcrafts',
//     'psychic_astrology',
//     'farms',
//     'german',
//     'eventservices',
//     'bicycles',
//     'japanese',
//     'hair',
//     'media',
//     'photographers',
//     'brazilian',
//     'martialarts',
//     'breweries',
//     'gourmet',
//     'cannabis_clinics',
//     'chinese',
//     'turkish',
//     'tastingclasses',
//     'gyms',
//     'latin',
//     'parks',
//     'caribbean',
//     'movietheaters',
//     'mexican',
//     'mideastern',
//     'skincare',
//     'mediterranean',
//     'belgian',
//     'flowers',
//     'diving',
//     'festivals',
//     'artclasses',
//     'donburi',
//     'gardening',
//     'hairremoval',
//     'malaysian',
//     'othersalons',
//     'breakfast_brunch',
//     'localflavor',
//     'zoos',
//     'polish',
//     'african',
//     'tanning',
//     'jpsweets',
//     'cafes',
//     'social_clubs',
//     'wineries',
// ]

// export default category_list

