# Generated by Django 4.0.3 on 2022-08-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_rest', '0003_remove_account_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthday',
        ),
    ]
